services:
  db:
    image: postgres:latest
    build: .
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create_database.sh:/docker-entrypoint-initdb.d/create_database.sh
      - ./.env:/docker-entrypoint-initdb.d/.env